# Generated by Django 5.2.5 on 2025-08-29 03:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'ягоды',
                'verbose_name_plural': 'ягоды',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Курьер')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон курьера')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'курьер',
                'verbose_name_plural': 'курьеры',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'декор',
                'verbose_name_plural': 'декоры',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'форма',
                'verbose_name_plural': 'формы',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='количество уровней')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'уровень',
                'verbose_name_plural': 'уровни',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'топпинг',
                'verbose_name_plural': 'топпинги',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Индивидуальный', max_length=50, verbose_name='название')),
                ('text', models.CharField(blank=True, max_length=75, verbose_name='надпись')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость, руб.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cake/', verbose_name='Изображение торта')),
                ('is_show', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображение')),
                ('berries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='storage.berry', verbose_name='ягоды')),
                ('decorations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='storage.decoration', verbose_name='декор')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='storage.form', verbose_name='форма торта')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='storage.level', verbose_name='количество уровней')),
            ],
            options={
                'verbose_name': 'торт',
                'verbose_name_plural': 'торты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unprocessed', 'Необработанный'), ('underway', 'В работе'), ('delivery', 'Доставка'), ('completed', 'Завершен')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус')),
                ('address', models.TextField(verbose_name='адрес')),
                ('order_notes', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='комментарий для курьера')),
                ('delivery_date', models.DateField(verbose_name='дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='время доставки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storage.cake', verbose_name='торт')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storage.courier', verbose_name='курьер')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
