# Generated by Django 5.2.5 on 2025-08-27 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cake',
            name='decorations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='storage.decoration', verbose_name='украшения'),
        ),
        migrations.AddField(
            model_name='cake',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='storage.form', verbose_name='форма торта'),
        ),
        migrations.AddField(
            model_name='cake',
            name='levels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='storage.level', verbose_name='количество уровней'),
        ),
        migrations.AddField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storage.cake', verbose_name='торт'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storage.courier', verbose_name='курьер'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='storage.topping', verbose_name='топпинг'),
        ),
    ]
