# Generated by Django 5.2.5 on 2025-09-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='LSKjAm4PTGKEyanJfbTz', max_length=20, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'реферальную ссылку',
                'verbose_name_plural': 'реферальные ссылки',
            },
        ),
    ]
