# Generated by Django 5.2.5 on 2025-09-01 18:19

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_clickcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcounter',
            name='token',
            field=models.CharField(default='3C3ntHjsAiox0vl285gC', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uniq_promocode_code_lower')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storage.promocode', verbose_name='Промокод'),
        ),
    ]
