# Generated by Django 5.2.5 on 2025-09-01 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_clickcounter_token_promocode_order_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='clickcounter',
            name='token',
            field=models.CharField(default='47YTx9p3h3N0TnTZUrG8', max_length=20, unique=True),
        ),
    ]
