services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend-migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./media:/app/media:rw
      - ./static:/app/static:rw
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - backend-migrate

